//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayer.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_musteri
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string tc { get; set; }
        public string cep_tel { get; set; }
        public string ev_tel { get; set; }
        public string is_tel { get; set; }
        public string ev_adress { get; set; }
        public string is_adress { get; set; }
        public string mail { get; set; }
        public Nullable<bool> durum { get; set; }
        public Nullable<bool> siradisiisim { get; set; }
    }
}
